language: node_js
node_js:
- '0.12'
before_script:
- npm install -g gulp
deploy:
  provider: npm
  api_key:
    secure: ck+XwLOhOrbWzG9PCP9wBOoMqZ5bjVsBjTAuVQsxrlob2yHXA2o2tDJWZ1qrw7KPtzucQJMDaJYVu9ZU18edw5d7r5jETtQlrJCXA2iJOCY4ZvIrO3qVGYWnQY/dFksWm5MOji+FmSemEsWw/fQVNqXzOHweSV83cyP0pbYAJPTgDZZG2DKnzdMb+nljZToqO2LPj5I06OdNOoA6PUcz3IOHSae3o34hPNIK814hc6Mr7Fr0ePJZivCEpS5+9LcwzWXKgc9fvShAZidQjkccxPctIlq1NlbuR2Oa5wlOrafjNMORjeZFmlmsSHBN9zZqu4iTdkrhlVHvJg/ZDA1y3btq+cA5HP14X6CIEtXvS9hHmauZsgAUCUMKjXnfS1bPyYc7ZnEPe/azBJJNSWlAk7F1gSzp1T4ZRxRXIVFUzUVZKFmJHYXAqNREfRXLyDmknSn4xcW7HjOYR2TDVOptq67Z35X3GM8cdgATU7lo8OrVWuXGnA13mHl0tirGiKiNK/QgfRbskBZ2fcAgvxr7RBz5WD35nvBMx/FMN8oIL33elGQ7O+gj6FzwDqwWRsr4amTKJZOjfPTe5u56cQ3932l2yEPkbgrAT4rBlmaOOkWwFwVfaaqVboufTgugo7yjHth+tx7oGfmhS61PJp/aS9GZRL2GRsL8W7vsosPWGfU=
  on:
    all_branches: true
    tags: true
    repo: bealearts/bindling
